spring.application.name=unimonpark
spring.datasource.url=jdbc:postgresql://192.168.10.214:5432/mi_base_datos?sslmode=disable&currentSchema=unimonpark
spring.datasource.username=admin_user
spring.datasource.password=MiPasswordSeguro123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql = true

jwt.secret=unimonpark-clave-secreta-super-larga-para-firmar-tokens-jwt-2026
jwt.expiration-ms=28800000
# Mail Configuration (TODO: Replace with actual password)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b68a2e7c213d1b
spring.mail.password=5f8a29201c36b8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
