spring.application.name=unimonpark
spring.datasource.url=jdbc:postgresql://192.168.10.214:5432/mi_base_datos?sslmode=disable&currentSchema=unimonpark
spring.datasource.username=admin_user
spring.datasource.password=MiPasswordSeguro123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql = true
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=unimonpark-clave-secreta-super-larga-para-firmar-tokens-jwt-2026
jwt.expiration-ms=28800000